---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mydeploy
spec:
    replicas: 5
    selector:
       matchLabels:
          app: swiggy
    template:
       metadata:
          labels:
             app: swiggy
       spec:
          containers:
             - name: cont01
               image: saikumar1817/trevis-project:v2
               ports:
                 - containerPort: 3000
